//! macOS sandbox-exec (SBPL) policy generation.
//!
//! Reads the static base profile and appends dynamic rules for the
//! working directory, worktrees, and extra directory grants.

use crate::config::ExtraDirs;
use crate::worktree::WorktreeInfo;
use std::fmt::Write;
use std::path::{Path, PathBuf};
use std::{fs, io};

/// Default location of the static base profile.
const DEFAULT_PROFILE_PATH: &str = ".config/sandbox-exec/agent.sb";

/// Resolve the static base profile path.
fn base_profile_path() -> PathBuf {
    dirs::home_dir()
        .expect("cannot determine home directory")
        .join(DEFAULT_PROFILE_PATH)
}

/// Emit SBPL ancestor literal grants for a path.
///
/// Produces `(allow file-read* (literal "/") (literal "/Users") ...)`
/// for each path component, enabling directory traversal.
fn emit_ancestors(path: &Path, out: &mut String) {
    let path_str = path.to_string_lossy();
    out.push_str("(allow file-read*\n");
    out.push_str("    (literal \"/\")\n");

    let mut cur = String::new();
    for component in path_str.trim_start_matches('/').split('/') {
        if component.is_empty() {
            continue;
        }
        cur.push('/');
        cur.push_str(component);
        writeln!(out, "    (literal \"{cur}\")").unwrap();
    }
    out.push_str(")\n");
}

/// Emit an SBPL read-write subpath grant.
fn emit_rw_grant(path: &Path, out: &mut String) {
    writeln!(
        out,
        "(allow file-read* file-write* (subpath \"{}\"))",
        path.display()
    )
    .unwrap();
}

/// Emit an SBPL read-only subpath grant.
fn emit_ro_grant(path: &Path, out: &mut String) {
    writeln!(
        out,
        "(allow file-read* (subpath \"{}\"))",
        path.display()
    )
    .unwrap();
}

/// Emit an SBPL deny rule for a path.
fn emit_deny(path: &Path, out: &mut String) {
    writeln!(
        out,
        "(deny file-read* file-write* (subpath \"{}\"))",
        path.display()
    )
    .unwrap();
}

/// Assemble the complete sandbox policy.
///
/// Reads the static base profile and appends dynamic rules for the
/// working directory, worktrees, and extra directory grants.
///
/// # Errors
/// Returns an error if the base profile cannot be read.
pub fn assemble_policy(
    workdir: &Path,
    worktree_info: &WorktreeInfo,
    extra_dirs: &ExtraDirs,
    deny_paths: &[PathBuf],
) -> Result<String, io::Error> {
    let base_path = base_profile_path();
    let mut policy = fs::read_to_string(&base_path)?;

    policy.push('\n');
    policy.push_str(";; ===========================================================================\n");
    policy.push_str(";; Dynamic rules -- generated by gator\n");
    writeln!(policy, ";; workdir: {}", workdir.display()).unwrap();
    policy.push_str(";; ===========================================================================\n\n");

    // Workdir grants
    writeln!(policy, ";; Workdir: {}", workdir.display()).unwrap();
    emit_ancestors(workdir, &mut policy);
    emit_rw_grant(workdir, &mut policy);
    policy.push('\n');

    // Git common dir (linked worktree)
    if let Some(common) = &worktree_info.common_dir {
        writeln!(policy, ";; Git common dir: {}", common.display()).unwrap();
        emit_ancestors(common, &mut policy);
        emit_rw_grant(common, &mut policy);
        policy.push('\n');
    }

    // Sibling worktrees (RO)
    for sibling in &worktree_info.siblings {
        writeln!(policy, ";; Sibling worktree: {}", sibling.display()).unwrap();
        emit_ancestors(sibling, &mut policy);
        emit_ro_grant(sibling, &mut policy);
        policy.push('\n');
    }

    // Extra RW dirs
    for dir in &extra_dirs.rw {
        writeln!(policy, ";; Extra RW: {}", dir.display()).unwrap();
        emit_ancestors(dir, &mut policy);
        emit_rw_grant(dir, &mut policy);
    }

    // Extra RO dirs
    for dir in &extra_dirs.ro {
        writeln!(policy, ";; Extra RO: {}", dir.display()).unwrap();
        emit_ancestors(dir, &mut policy);
        emit_ro_grant(dir, &mut policy);
    }

    // Policy denies
    if !deny_paths.is_empty() {
        writeln!(policy, "\n;; Policy denies").unwrap();
        for dir in deny_paths {
            writeln!(policy, ";; Deny: {}", dir.display()).unwrap();
            emit_deny(dir, &mut policy);
        }
    }

    Ok(policy)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    #[test]
    fn emit_ancestors_simple() {
        let mut out = String::new();
        emit_ancestors(Path::new("/Users/jfb/Projects"), &mut out);
        assert!(out.contains("(literal \"/\")"));
        assert!(out.contains("(literal \"/Users\")"));
        assert!(out.contains("(literal \"/Users/jfb\")"));
        assert!(out.contains("(literal \"/Users/jfb/Projects\")"));
    }

    #[test]
    fn emit_rw_grant_format() {
        let mut out = String::new();
        emit_rw_grant(Path::new("/Users/jfb/Work"), &mut out);
        assert_eq!(
            out,
            "(allow file-read* file-write* (subpath \"/Users/jfb/Work\"))\n"
        );
    }

    #[test]
    fn emit_ro_grant_format() {
        let mut out = String::new();
        emit_ro_grant(Path::new("/Users/jfb/Data"), &mut out);
        assert_eq!(
            out,
            "(allow file-read* (subpath \"/Users/jfb/Data\"))\n"
        );
    }

    #[test]
    fn assemble_policy_includes_dynamic_section() {
        // This test requires the static base profile to exist.
        // Skip if not present (CI environments).
        let base = dirs::home_dir().unwrap().join(DEFAULT_PROFILE_PATH);
        if !base.exists() {
            return;
        }

        let workdir = Path::new("/Users/jfb/Projects/test");
        let wt = WorktreeInfo::default();
        let extras = ExtraDirs::default();

        let policy = assemble_policy(workdir, &wt, &extras, &[]).unwrap();
        assert!(policy.contains("(deny default)"));
        assert!(policy.contains("Dynamic rules"));
        assert!(policy.contains("/Users/jfb/Projects/test"));
    }

    #[test]
    fn emit_deny_format() {
        let mut out = String::new();
        emit_deny(Path::new("/Users/jfb/.aws"), &mut out);
        assert_eq!(
            out,
            "(deny file-read* file-write* (subpath \"/Users/jfb/.aws\"))\n"
        );
    }

    #[test]
    fn assemble_policy_with_denies() {
        let base = dirs::home_dir().unwrap().join(DEFAULT_PROFILE_PATH);
        if !base.exists() {
            return;
        }

        let workdir = Path::new("/Users/jfb/Projects/test");
        let wt = WorktreeInfo::default();
        let extras = ExtraDirs::default();
        let denies = vec![PathBuf::from("/Users/jfb/.secret")];

        let policy = assemble_policy(workdir, &wt, &extras, &denies).unwrap();
        assert!(policy.contains("Policy denies"));
        assert!(policy.contains("(deny file-read* file-write* (subpath \"/Users/jfb/.secret\"))"));
    }
}
